FROM node:16-alpine3.15 as builder

RUN yarn set version berry

WORKDIR /app

COPY . .
RUN yarn install

RUN mkdir -p /app/storage
RUN chown -R node:node /app/storage
USER node
ENTRYPOINT npx ts-node-dev --respawn index.ts
