FROM node:16-alpine3.15 as builder

RUN addgroup -S hypertube && adduser -S hypertube -G hypertube
RUN yarn set version berry

WORKDIR /app

COPY . .
RUN yarn install

RUN mkdir -p /app/storage
RUN chown -R hypertube:hypertube /app/storage
USER hypertube
ENTRYPOINT npx ts-node-dev --respawn index.ts
