const initial = [
	[
		'/background/r9uVYK7MNBTkREv0caUMRKB2IkY.jpg',
		'/background/zLJr2jRhXPAlYKGc82lA9jUOZjV.jpg',
		'/background/cx2UyLOm3BdLopPSooFEV3LA3fr.jpg',
		'/background/4Tw8TB9ikrcgzJgR0LOvgfnXD74.jpg',
		'/background/5oRyUjQCD9bMXv0oSvUYiJsQlqd.jpg',
		'/background/b3XrfXvFKHBXQTTAQbQBJ0k11Rl.jpg',
		'/background/kSMarEm3ESOOr11dzsep2RZ1ClD.jpg',
		'/background/ucLdEGaIFlpIdGlkzYj2OcXbGhz.jpg',
		'/background/uJvMXO1DNEER2lZocNjJy2zXtYs.jpg',
		'/background/2zdzBvEsqXDs0484WiOZiKLkDV8.jpg'
	],
	[
		'/background/1BoXSfwY53Qwxu2B42MHs3d4DEY.jpg',
		'/background/v28T5F1IygM8vXWZIycfNEm3xcL.jpg',
		'/background/b1z84OMbtzmFWsiQWyonoPqWY2Z.jpg',
		'/background/4Gzgvmh56OgZrEYyUzqBT09CfO.jpg',
		'/background/uzjTcOgolUO94a6VMqmjNQLlt6d.jpg',
		'/background/qlJT0deZBto3Sx7s0XHtfvKGV1S.jpg',
		'/background/bo4ZsMQNDZMKIGBVDS80thiGVO2.jpg',
		'/background/uU3YoLSaVBOaMryzhuiiRWDFbIw.jpg',
		'/background/qOLfQQhXGIMjR008mTn9odNtorP.jpg',
		'/background/8QGrXDJMENtLrC87zSypsQktkRb.jpg'
	],
	[
		'/background/kIXtt9GejWPNstOuqKEgEVEdA6b.jpg',
		'/background/6I2EuxaVNevimghE3g2E68p8V8u.jpg',
		'/background/kTh1s6I6yUyk2OGiRoGkDTYTS6K.jpg',
		'/background/1rVNiPMAHOyxjkdwyTtqUQs0i61.jpg',
		'/background/7Xr68P8h2V7P9rwh7Eb6wwpSTUR.jpg',
		'/background/arfzjn1tGvXWwkX7eaGVuXsc0mp.jpg',
		'/background/cxHQB6LJz6EUEnnYfBv9o3XWdPe.jpg',
		'/background/zkGFADykBtfPfTv7YJooxTH52ph.jpg',
		'/background/3SyG7dq2q0ollxJ4pSsrqcfRmVj.jpg',
		'/background/cRFWtZIyPing73YhMrsp3W1uBO4.jpg'
	],
	[
		'/background/cx2UyLOm3BdLopPSooFEV3LA3fr.jpg',
		'/background/d2praYsQxyDtKM67iEanSS418fH.jpg',
		'/background/2sjgX7DUo6AL4OfXQPXq1DprFk2.jpg',
		'/background/7RSCL6V8BlekgVnNPok6tLW50tP.jpg',
		'/background/ptZP919Q3hHSSITMekPCYdl172K.jpg',
		'/background/6wfZujKSQHfsEXyAdOFdCj29x6U.jpg',
		'/background/kPzQtr5LTheO0mBodIeAXHgthYX.jpg',
		'/background/hangTmbxpSV4gpHG7MgSlCWSSFa.jpg',
		'/background/jW4OW6ySAtP40BzUWgVmsApqyaS.jpg',
		'/background/rK8s7bTDZiOs41FXsOcoSv8X9Y5.jpg'
	],
	[
		'/background/iMpFWThfGzGJvAJYyFNTsrBQrF2.jpg',
		'/background/iT5otbDVNOLpeYN3nkfZ9FP2BQT.jpg',
		'/background/uXs7wMtsfnBFuGVogAxJXZXshFU.jpg',
		'/background/jBCUJ90BVXIDSLlXUvgQcj6LOHa.jpg',
		'/background/7InGE2Sux0o9WGbbn0bl7nZzqEc.jpg',
		'/background/hk0JZyTHfgN35f43pJUhDPTNjM0.jpg',
		'/background/9HFFwZOTBB7IPFmn9E0MXdWave3.jpg',
		'/background/TUmSO5EPIZAfRSOEjmbrgbTw8i.jpg',
		'/background/iNV2wiYpSBXJuFeEZUHC92zgcdl.jpg',
		'/background/3fTjxkrp23AWyRbMKaujz5wrNDM.jpg'
	],
	[
		'/background/kmWpbWYu4gT7wIV4amP0gMDjNHj.jpg',
		'/background/xBoIe0eX9UuSSPe5Qt6KXIQOd3I.jpg',
		'/background/wWehjjuY02MlyWM9GvLBsGl5mj.jpg',
		'/background/kqYDoEb9PxLXM2ccoHInMMJalti.jpg',
		'/background/zrmpx6UpMPx3jic6i74yZiEPdIk.jpg',
		'/background/riLxHFjEe15pkAIB1ng9qB2UnjQ.jpg',
		'/background/ep2C0shFTkxPUGLBvsgODWycwU7.jpg',
		'/background/75s7inwv1WHRuySyjA6p0oMaz9Z.jpg',
		'/background/5oRyUjQCD9bMXv0oSvUYiJsQlqd.jpg',
		'/background/ba6CNrM9CdSVGR61NUHJ1uDfmLz.jpg'
	],
	[
		'/background/6zltP23zLGPogsHZUazSrrwNuKs.jpg',
		'/background/t9JGg10CW1DzXEdWL54ewkUko6N.jpg',
		'/background/yVGSH5HTTnxJ3SlkDNA8xYP3Gu3.jpg',
		'/background/rtfGeS5WMXA6PtikIYUmYTSbVdg.jpg',
		'/background/7iMAzRhaw2OYbIFNlkeZ6CldMhA.jpg',
		'/background/uhE1v8Td7k4csrTV5Xfvvh0V6jD.jpg',
		'/background/9cIMdubOXL3A82yCoBYdF1u4lNW.jpg',
		'/background/uTCfTibqtk4f90cC59bLPMOmsfc.jpg',
		'/background/avokvOwhjVR9GgISsSSgb2A343G.jpg',
		'/background/xsjgiztyEu9cEZetxFlvJz6Yibw.jpg'
	],
	[
		'/background/uSoTF1bTwkhJGljRvz3XQrzpTvm.jpg',
		'/background/yFwFp5QVHazxTklKGiJ0G59pVab.jpg',
		'/background/fCKDii2vGindtC2UhhV53TioBgk.jpg',
		'/background/2zdzBvEsqXDs0484WiOZiKLkDV8.jpg',
		'/background/n46rT8fTXesVBXzUwLGkWCHHuIC.jpg',
		'/background/u9JXGdxsb7jbRhqaeVWzCBwiY19.jpg',
		'/background/ug8X5UkgdvcZ0WW0WNo5p0F1NGn.jpg',
		'/background/5hTK0J9SGPLSTFwcbU0ELlJsnAY.jpg',
		'/background/9j21DXo7Gwtfxj81iC20AbOqumt.jpg',
		'/background/u6Pg9eTklhg6Aa7kXaxrfdE1Chi.jpg'
	]
];

export default initial.map((line) => [...line, ...line, ...line]);
