version: "3.8"
services:
  api:
    build: ./api
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - ./api:/app
    # command: go test # ???
    depends_on:
      - postgres
      # - redis
    links:
      - postgres
      # - redis
    ports:
      - "5051:5051"

    # access to the server:
    # $> docker-compose exec server sh
    
    # go test (only logic part):
    # $> docker-compose exec server gp test ./logic

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGUSER: ${PGUSER}         # psql
      PGPASSWORD: ${PGPASSWORD} # psql
      PGDATABASE: ${PGDATABASE} # psql
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

    # access to the psql CLI (to fizzbuzz database):
    # $> docker-compose exec postgres psql

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres
    ports:
      - "5050:80"
    restart: unless-stopped
    links:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres-data:
    driver: local
  pgadmin-data:
    driver: local
  # redis-data:
  #   driver: local