version: "3.8"
services:
  api-auth:
    build:
      context: ./
      dockerfile: ./api-auth/Dockerfile
    env_file:
      - ./.env
      - ./client/.env
      - ./api-auth/.env
      - ./postgres/.env
      - ./redis/.env
    depends_on:
      - postgres
      - redis
    restart: on-failure
    links:
      - postgres
      - redis
    ports:
      - "${API_AUTH_GRPC_PORT}:${API_AUTH_GRPC_PORT}"
      - "${API_AUTH_GRPC_GATEWAY_PORT}:${API_AUTH_GRPC_GATEWAY_PORT}"
      - "${API_AUTH_HTTP_PORT}:${API_AUTH_HTTP_PORT}"

  api-user:
    build:
      context: ./
      dockerfile: ./api-user/Dockerfile
    env_file:
      - ./api-user/.env
      - ./postgres/.env
      - ./redis/.env
    depends_on:
      - postgres
      - redis
    restart: on-failure
    links:
      - postgres
      - redis
    ports:
      - "${API_USER_GRPC_PORT}:${API_USER_GRPC_PORT}"
      - "${API_USER_GRPC_GATEWAY_PORT}:${API_USER_GRPC_GATEWAY_PORT}"
    # access to the server:
    # $> docker-compose exec server sh

  api-scrapper:
    build:
      context: ./
      dockerfile: ./api-scrapper/Dockerfile
    env_file:
      - ./api-scrapper/.env
      - ./postgres/.env
    depends_on:
      - postgres
    restart: on-failure
    links:
      - postgres
    ports:
      - "${API_SCRAPPER_GRPC_PORT}:${API_SCRAPPER_GRPC_PORT}"

  api-media:
    build:
      context: ./
      dockerfile: ./api-media/Dockerfile
    env_file:
      - ./api-scrapper/.env
      - ./api-media/.env
      - ./postgres/.env
      - ./redis/.env
    volumes:
      - streaming-data:/app/.cache
    depends_on:
      - postgres
      - api-scrapper
      - redis
    restart: on-failure
    links:
      - postgres
      - api-scrapper
      - redis
    ports:
      - "${API_MEDIA_GRPC_PORT}:${API_MEDIA_GRPC_PORT}"
      - "${API_MEDIA_GRPC_GATEWAY_PORT}:${API_MEDIA_GRPC_GATEWAY_PORT}"

  api-streaming:
    build: ./api-streaming
    env_file:
      - ./.env
      - ./postgres/.env
      - ./redis/.env
      - ./client/.env
      - ./api-streaming/.env
    depends_on:
      - postgres
    restart: on-failure
    links:
      - postgres
    ports:
      - "${API_STREAMING_PORT}:${API_STREAMING_PORT}"

  api-position:
    build: ./api-position
    env_file:
      - ./.env
      - ./postgres/.env
      - ./redis/.env
      - ./client/.env
      - ./api-position/.env
    depends_on:
      - postgres
      - redis
    restart: on-failure
    links:
      - postgres
      - redis
    ports:
      - "${API_POSITION_PORT}:${API_POSITION_PORT}"

  test-meta:
    build: ./test/meta
    env_file:
      - ./client/.env
      - ./api-auth/.env
      - ./api-user/.env
      - ./api-position/.env
      - ./api-media/.env
      - ./redis/.env
    volumes:
      - ./test/meta:/app
      - /app/node_modules
      - /app/.yarn
    depends_on:
      - client
      - api-auth
      - api-user
      - api-position
      - api-media
      - redis
    links:
      - client
      - api-auth
      - api-user
      - api-position
      - api-media
      - redis
    profiles:
      - test

  postgres:
    image: postgres:14.4-alpine
    restart: always
    env_file:
      - ./postgres/.env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    # access to the psql CLI:
    # $> docker-compose exec postgres psql

  redis:
    image: redis:7.0.2-alpine
    command: --port ${REDIS_PORT}
    env_file:
      - ./redis/.env
    volumes:
      - redis-data:/data
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    # access to the redis CLI:
    # $> dc exec -it redis /bin/sh -c 'redis-cli -h redis'

  adminer:
    image: adminer:4.8.1-standalone
    depends_on:
      - postgres
    ports:
      - 5050:8080
    restart: unless-stopped
    links:
      - postgres

  tmdb-proxy:
    image: nginx:1.23-alpine
    env_file:
      - ./tmdb-proxy/.env
    volumes:
      - ./tmdb-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx-proxy-data:/var/www/cache
    ports:
      - "${TMDB_PROXY_PORT}:80"

  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
      - ./api-auth/.env
      - ./api-user/.env
      - ./api-media/.env
      - ./api-streaming/.env
      - ./tmdb-proxy/.env
      - ./client/.env
    depends_on:
      - api-auth
      - api-user
      - api-media
      - api-streaming
      - api-position
    links:
      - api-auth
      - api-media
      - api-streaming
      - api-position
      - tmdb-proxy
    ports:
      - "${CLIENT_PORT}:3000"

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local
  nginx-proxy-data:
    driver: local
  streaming-data:
    driver: local

