version: "3.8"
services:
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
      - ./api-auth/.env
      - ./api-user/.env
      - ./api-media/.env
      - ./api-streaming/.env
      - ./tmdb-proxy/.env
      - ./client/.env
    ports:
      - "${CLIENT_PORT}:3000"
    restart: unless-stopped

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local
