version: "3.8"
services:
  api-auth:
    build: ./api-auth
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      API_AUTH_PORT: ${API_AUTH_PORT}
    volumes:
      - ./api-auth:/app
    # command: go test # ???
    depends_on:
      - postgres
      # - redis
    links:
      - postgres
      # - redis
    ports:
      - "${API_AUTH_PORT}:${API_AUTH_PORT}"

    # access to the server:
    # $> docker-compose exec server sh
  
    # go test (only logic part):
    # $> docker-compose exec server gp test ./logic

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGUSER: ${PGUSER}         # psql
      PGPASSWORD: ${PGPASSWORD} # psql
      PGDATABASE: ${PGDATABASE} # psql
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

    # access to the psql CLI (to fizzbuzz database):
    # $> docker-compose exec postgres psql

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres
    ports:
      - "5050:80"
    restart: unless-stopped
    links:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  
  client:
    build: ./client
    environment:
      CLIENT_PORT: ${CLIENT_PORT}
    volumes:
      - ./client:/app
    depends_on:
      - api-auth
    links:
      - api-auth
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"

volumes:
  postgres-data:
    driver: local
  pgadmin-data:
    driver: local
  # redis-data:
  #   driver: local