FROM node:16-alpine3.15 as builder

# Install ffmpeg for transcode
RUN apk add --no-cache ffmpeg

RUN yarn set version berry

WORKDIR /app

COPY . .
RUN yarn install

RUN mkdir -p /app/.cache
RUN chown -R node:node /app/.cache
USER node
ENTRYPOINT npx ts-node-dev --respawn index.ts
