// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"database/sql"
)

type User struct {
	ID        int64
	Username  string
	Firstname string
	Lastname  string
	Email     string
	ID42      sql.NullInt32
	Password  sql.NullString
}
