# https://levelup.gitconnected.com/docker-for-go-development-a27141f36ba9
FROM golang:1.18.3-alpine3.16

# copy api files
WORKDIR /hypertube/app
COPY ./api-user /hypertube/app
COPY ./.shared /hypertube/.shared

# install api dependencies
RUN go mod download

# install CompileDaemon (hot reload)
RUN go get github.com/githubnemo/CompileDaemon
RUN go install -v github.com/githubnemo/CompileDaemon

ENTRYPOINT CompileDaemon --build="go build main.go" --command=./main
